"""
QABook Export Constants

Shared constants used across all Excel exports.
"""


class ExportConstants:
    """Common constants for QABook export documents."""

    # ---------------------------------
    # Application
    # ---------------------------------

    APP_NAME = "QABook"

    # ---------------------------------
    # QABook Documentation Standard
    # ---------------------------------

    QDS_VERSION = "1.0"

    # ---------------------------------
    # Sheet Names
    # ---------------------------------

    REQUIREMENTS_SHEET = "Requirements"

    # ---------------------------------
    # Document Titles
    # ---------------------------------

    REQUIREMENTS_DOCUMENT_TITLE = "Requirements Document"

    # ---------------------------------
    # Metadata Labels
    # ---------------------------------

    PROJECT_NAME_LABEL = "Project Name"

    PROJECT_CODE_LABEL = "Project Code"

    GENERATED_BY_LABEL = "Generated By"

    GENERATED_DATE_LABEL = "Generated Date"

    VERSION_LABEL = "Version"

    TEST_CASES_SHEET = "Test Cases"

    TEST_CASES_DOCUMENT_TITLE = "Test Cases Document"

    TEST_SUITES_SHEET = "Test Suites"

    TEST_SUITES_DOCUMENT_TITLE = "Test Suites Document"

    TEST_RUNS_SHEET = "Test Runs"

    TEST_RUNS_DOCUMENT_TITLE = "Test Runs Document"

    BUGS_SHEET = "Bugs"

    BUGS_DOCUMENT_TITLE = "Bug Report"