import json
import re
from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from app.automation.models.automation_project import (
    AutomationProject,
)


class FrameworkGeneratorService:
    def generate(
        self,
        automation_project: AutomationProject,
    ) -> BytesIO:
        buffer = BytesIO()

        with ZipFile(
            buffer,
            "w",
            ZIP_DEFLATED,
        ) as zip_file:
            # Root files
            self._add_file(
                zip_file,
                "README.md",
                self._readme_content(
                    automation_project
                ),
            )

            self._add_file(
                zip_file,
                "requirements.txt",
                self._requirements_content(),
            )

            self._add_file(
                zip_file,
                "pytest.ini",
                self._pytest_ini_content(),
            )

            self._add_file(
                zip_file,
                "conftest.py",
                self._conftest_content(),
            )

            self._add_file(
                zip_file,
                ".env.example",
                self._env_example_content(),
            )

            self._add_file(
                zip_file,
                ".gitignore",
                self._gitignore_content(),
            )

            # QABook metadata
            self._add_file(
                zip_file,
                "qabook/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "qabook/manifest.json",
                self._manifest_content(
                    automation_project
                ),
            )

            # Pages
            self._add_file(
                zip_file,
                "pages/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "pages/base_page.py",
                self._base_page_content(),
            )

            # Fixtures
            self._add_file(
                zip_file,
                "fixtures/__init__.py",
                "",
            )

            # Utils
            self._add_file(
                zip_file,
                "utils/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "utils/config.py",
                self._config_content(),
            )

            self._add_file(
                zip_file,
                "utils/manifest.py",
                self._manifest_loader_content(),
            )

            self._add_file(
                zip_file,
                "utils/qabook_client.py",
                self._qabook_client_content(),
            )

            # Tests
            self._add_file(
                zip_file,
                "tests/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "tests/ui/__init__.py",
                "",
            )

            # Test data and reports
            self._add_file(
                zip_file,
                "test_data/.gitkeep",
                "",
            )

            self._add_file(
                zip_file,
                "reports/.gitkeep",
                "",
            )

            # Generate mapped tests
            for mapping in automation_project.mappings:
                self._add_test_file(
                    zip_file,
                    mapping.test_file_path,
                    mapping.test_name,
                )

        buffer.seek(0)

        return buffer

    @staticmethod
    def _add_file(
        zip_file: ZipFile,
        file_path: str,
        content: str,
    ) -> None:
        zip_file.writestr(
            file_path,
            content,
        )

    def _add_test_file(
        self,
        zip_file: ZipFile,
        file_path: str,
        test_name: str,
    ) -> None:
        safe_path = file_path.replace(
            "\\",
            "/",
        ).lstrip("/")

        if ".." in safe_path.split("/"):
            return

        # Automation test files must remain inside tests/.
        if not safe_path.startswith("tests/"):
            safe_path = f"tests/{safe_path}"

        file_name = safe_path.split("/")[-1]

        if not file_name.endswith(".py"):
            file_name = f"{file_name}.py"

        safe_path = (
            "/".join(safe_path.split("/")[:-1])
            + "/"
            + file_name
        )

        safe_test_name = re.sub(
            r"[^0-9a-zA-Z_]",
            "_",
            test_name,
        )

        if safe_test_name and safe_test_name[0].isdigit():
            safe_test_name = f"test_{safe_test_name}"

        content = f'''import pytest


@pytest.mark.automation
def {safe_test_name}():
    """
    Automation placeholder generated by QABook.

    Implement the actual Playwright test here.
    """
    pytest.skip(
        "Automation test not implemented yet."
    )
'''

        self._add_file(
            zip_file,
            safe_path,
            content,
        )

    @staticmethod
    def _manifest_content(
        automation_project: AutomationProject,
    ) -> str:
        tests = []

        for mapping in automation_project.mappings:
            safe_path = mapping.test_file_path.replace(
                "\\",
                "/",
            ).lstrip("/")

            if ".." in safe_path.split("/"):
                continue

            if not safe_path.startswith("tests/"):
                safe_path = f"tests/{safe_path}"

            file_name = safe_path.split("/")[-1]

            if not file_name.endswith(".py"):
                file_name = f"{file_name}.py"

            safe_path = (
                "/".join(safe_path.split("/")[:-1])
                + "/"
                + file_name
            )

            tests.append(
                {
                    "test_case_id": mapping.test_case_id,
                    "file": safe_path,
                }
            )

        return json.dumps(
            {
                "tests": tests,
            },
            indent=2,
        ) + "\n"

    @staticmethod
    def _readme_content(
        automation_project: AutomationProject,
    ) -> str:
        return f"""# {automation_project.name}

Automation framework generated by QABook.

## Framework

Python + pytest + Playwright

## Project Structure

    .
    ├── tests/
    │   └── ui/
    ├── pages/
    ├── fixtures/
    ├── utils/
    ├── qabook/
    │   ├── __init__.py
    │   └── manifest.json
    ├── test_data/
    ├── reports/
    ├── conftest.py
    ├── pytest.ini
    ├── requirements.txt
    ├── .env.example
    ├── .gitignore
    └── README.md

## Setup

Create and activate a virtual environment:

    python -m venv .venv

### Windows

    .venv\\Scripts\\activate

### Linux/macOS

    source .venv/bin/activate

Install dependencies:

    pip install -r requirements.txt

Install Playwright browsers:

    playwright install

## Environment

Copy `.env.example` to `.env` and configure the test environment.

Example:

    BASE_URL=https://example.com
    QABOOK_API_URL=http://127.0.0.1:8000

For QABook execution reporting, the automation
token is supplied at runtime through:

    QABOOK_AUTOMATION_TOKEN

The token should not be stored in `.env`.

## Run Tests

Run all automation tests:

    pytest

Run only automation tests:

    pytest -m automation

Normal local pytest execution does not require
a QABook token.

For CI/CD or another QABook-controlled execution
environment, provide:

    QABOOK_AUTOMATION_TOKEN=<AUTOMATION_TOKEN>

The existing CLI option can also be used as an
explicit override:

    pytest --qabook-token <AUTOMATION_TOKEN>

## QABook Integration

This framework uses QABook Test Cases as the
business reference.

Automation mappings are represented in:

    qabook/manifest.json

The manifest maintains the relationship between a
QABook Test Case ID and its automation test file.

Example:

    {{
      "tests": [
        {{
          "test_case_id": 95,
          "file": "tests/tc-002.py"
        }}
      ]
    }}

QABook-specific Test Case IDs are intentionally kept
outside the automation test source code.

When a QABook automation token is supplied at runtime,
the framework can resolve the Test Executions belonging
to that Test Run and associate mapped automation tests
with their corresponding QABook Test Cases.

## Page Objects

Reusable UI page behavior should be implemented inside:

    pages/

The `BasePage` class provides common Playwright page
operations that can be shared by page objects.

## Test Data

Test data can be stored inside:

    test_data/

## Reports

Generated reports and execution artifacts can be stored
inside:

    reports/

QABook also stores execution-level results so they can
be displayed in the QABook Reports workspace.
"""

    @staticmethod
    def _requirements_content() -> str:
        return """pytest
playwright
pytest-playwright
python-dotenv
requests
"""

    @staticmethod
    def _pytest_ini_content() -> str:
        return """[pytest]
testpaths = tests

python_files =
    test_*.py
    *_test.py
    tc*.py

markers =
    automation: QABook automation tests
"""

    @staticmethod
    def _conftest_content() -> str:
        return '''import os
from pathlib import Path

import pytest
from dotenv import load_dotenv

from utils.manifest import get_test_case_id_for_file
from utils.qabook_client import QABookClient


load_dotenv()


@pytest.fixture(scope="session")
def base_url():
    return os.getenv(
        "BASE_URL",
        "https://example.com",
    )


def pytest_addoption(parser):
    parser.addoption(
        "--qabook-token",
        action="store",
        default=None,
        help="Optional QABook automation token override.",
    )


@pytest.fixture(scope="session")
def qabook_token(pytestconfig):
    """
    Resolve the QABook automation token.

    Priority:
    1. Explicit --qabook-token CLI option
    2. QABOOK_AUTOMATION_TOKEN environment variable

    Normal local execution does not require either.
    """
    cli_token = pytestconfig.getoption(
        "--qabook-token"
    )

    if cli_token:
        return cli_token

    return os.getenv(
        "QABOOK_AUTOMATION_TOKEN"
    )


@pytest.fixture(scope="session")
def qabook_executions(qabook_token):
    """
    Load all QABook Test Executions belonging
    to the current automation Test Run.
    """
    if not qabook_token:
        return []

    client = QABookClient()

    return client.get_executions_by_token(
        qabook_token,
    )


@pytest.fixture
def qabook_test_case_id(request):
    """
    Resolve the QABook Test Case ID for the
    current pytest test through manifest.json.
    """
    test_file = Path(
        request.node.fspath
    ).resolve()

    project_root = Path(
        request.config.rootdir
    ).resolve()

    try:
        relative_file = test_file.relative_to(
            project_root
        )
    except ValueError:
        return None

    return get_test_case_id_for_file(
        relative_file.as_posix()
    )


@pytest.fixture
def qabook_client():
    """
    Provide a QABook API client.
    """
    return QABookClient()


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(
    item,
    call,
):
    """
    Capture the final pytest test report.
    """
    outcome = yield

    report = outcome.get_result()

    if report.when == "call":
        item.qabook_test_report = report


def pytest_runtest_teardown(
    item,
    nextitem,
):
    """
    Report a passed mapped test to QABook.

    QABook reporting is completely disabled when
    no automation token is supplied.
    """
    token = item.config.getoption(
        "--qabook-token"
    ) or os.getenv(
        "QABOOK_AUTOMATION_TOKEN"
    )

    if not token:
        return

    report = getattr(
        item,
        "qabook_test_report",
        None,
    )

    if report is None:
        return

    if not report.passed:
        return

    test_file = Path(
        item.fspath
    ).resolve()

    project_root = Path(
        item.config.rootdir
    ).resolve()

    try:
        relative_file = test_file.relative_to(
            project_root
        )
    except ValueError:
        return

    test_case_id = get_test_case_id_for_file(
        relative_file.as_posix()
    )

    if test_case_id is None:
        return

    client = QABookClient()

    execution = client.get_execution_by_token_and_test_case(
        token,
        test_case_id,
    )

    client.update_test_execution(
        execution["id"],
        "Passed",
    )
'''

    @staticmethod
    def _manifest_loader_content() -> str:
        return """import json
from pathlib import Path


MANIFEST_PATH = (
    Path(__file__).resolve().parent.parent
    / "qabook"
    / "manifest.json"
)


def load_manifest() -> list[dict]:
    if not MANIFEST_PATH.exists():
        return []

    with MANIFEST_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        data = json.load(file)

    return data.get("tests", [])


def get_test_case_id_for_file(
    test_file: str,
) -> int | None:
    normalized_file = test_file.replace(
        "\\\\",
        "/",
    ).lstrip("./")

    for item in load_manifest():
        manifest_file = item.get("file", "")

        manifest_file = manifest_file.replace(
            "\\\\",
            "/",
        ).lstrip("./")

        if manifest_file == normalized_file:
            return item.get("test_case_id")

    return None
"""

    @staticmethod
    def _base_page_content() -> str:
        return """from playwright.sync_api import Page


class BasePage:
    def __init__(self, page: Page):
        self.page = page

    def navigate(self, url: str) -> None:
        self.page.goto(url)

    def get_title(self) -> str:
        return self.page.title()
"""

    @staticmethod
    def _config_content() -> str:
        return """import os


BASE_URL = os.getenv(
    "BASE_URL",
    "https://example.com",
)

QABOOK_API_URL = os.getenv(
    "QABOOK_API_URL",
    "http://127.0.0.1:8000",
)
"""

    @staticmethod
    def _qabook_client_content() -> str:
        return """import requests

from utils.config import QABOOK_API_URL


class QABookClient:
    def __init__(self):
        self.base_url = QABOOK_API_URL.rstrip("/")

    def get_executions_by_token(
        self,
        automation_token: str,
    ):
        response = requests.get(
            f"{self.base_url}/test-executions/token/"
            f"{automation_token}",
            timeout=30,
        )

        response.raise_for_status()

        return response.json()

    def get_execution_by_token_and_test_case(
        self,
        automation_token: str,
        test_case_id: int,
    ):
        response = requests.get(
            f"{self.base_url}/test-executions/token/"
            f"{automation_token}/test-case/{test_case_id}",
            timeout=30,
        )

        response.raise_for_status()

        return response.json()

    def update_test_execution(
        self,
        execution_id: int,
        status: str,
    ):
        response = requests.put(
            f"{self.base_url}/test-executions/{execution_id}",
            json={
                "status": status,
            },
            timeout=30,
        )

        response.raise_for_status()

        return response.json()
"""

    @staticmethod
    def _env_example_content() -> str:
        return """BASE_URL=https://example.com
QABOOK_API_URL=http://127.0.0.1:8000
"""

    @staticmethod
    def _gitignore_content() -> str:
        return """# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd

# Virtual environment
.venv/
venv/
env/

# Environment files
.env

# Playwright
test-results/
playwright-report/
blob-report/

# Reports and artifacts
reports/*
!reports/.gitkeep

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"""
