from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from app.automation.models.automation_project import (
    AutomationProject,
)


class FrameworkGeneratorService:
    def generate(
        self,
        automation_project: AutomationProject,
    ) -> BytesIO:
        buffer = BytesIO()

        with ZipFile(
            buffer,
            "w",
            ZIP_DEFLATED,
        ) as zip_file:
            # Root files
            self._add_file(
                zip_file,
                "README.md",
                self._readme_content(
                    automation_project
                ),
            )

            self._add_file(
                zip_file,
                "requirements.txt",
                self._requirements_content(),
            )

            self._add_file(
                zip_file,
                "pytest.ini",
                self._pytest_ini_content(),
            )

            self._add_file(
                zip_file,
                "conftest.py",
                self._conftest_content(),
            )

            self._add_file(
                zip_file,
                ".env.example",
                self._env_example_content(),
            )

            self._add_file(
                zip_file,
                ".gitignore",
                self._gitignore_content(),
            )

            # Pages
            self._add_file(
                zip_file,
                "pages/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "pages/base_page.py",
                self._base_page_content(),
            )

            # Fixtures
            self._add_file(
                zip_file,
                "fixtures/__init__.py",
                "",
            )

            # Utils
            self._add_file(
                zip_file,
                "utils/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "utils/config.py",
                self._config_content(),
            )

            self._add_file(
                zip_file,
                "utils/qabook_client.py",
                self._qabook_client_content(),
            )

            # Tests
            self._add_file(
                zip_file,
                "tests/__init__.py",
                "",
            )

            self._add_file(
                zip_file,
                "tests/ui/__init__.py",
                "",
            )

            # Test data and reports
            self._add_file(
                zip_file,
                "test_data/.gitkeep",
                "",
            )

            self._add_file(
                zip_file,
                "reports/.gitkeep",
                "",
            )

            # Generate mapped tests
            for mapping in automation_project.mappings:
                self._add_test_file(
                    zip_file,
                    mapping.test_file_path,
                    mapping.test_name,
                    mapping.test_case_id,
                )

        buffer.seek(0)

        return buffer

    @staticmethod
    def _add_file(
        zip_file: ZipFile,
        file_path: str,
        content: str,
    ) -> None:
        zip_file.writestr(
            file_path,
            content,
        )

    def _add_test_file(
        self,
        zip_file: ZipFile,
        file_path: str,
        test_name: str,
        test_case_id: int,
    ) -> None:
        safe_path = file_path.replace(
            "\\",
            "/",
        ).lstrip("/")

        if ".." in safe_path.split("/"):
            return

        # Automation test files must remain inside tests/.
        if not safe_path.startswith("tests/"):
            safe_path = f"tests/{safe_path}"

        file_name = safe_path.split("/")[-1]

        if not file_name.endswith(".py"):
            file_name = f"{file_name}.py"

        safe_path = (
            "/".join(safe_path.split("/")[:-1])
            + "/"
            + file_name
        )

        content = f'''import pytest


@pytest.mark.automation
@pytest.mark.qabook_test_case({test_case_id})
def {test_name}():
    """
    Automation placeholder for QABook test case.

    Implement the actual test steps here.
    """
    pytest.skip(
        "Automation test not implemented yet."
    )
'''

        self._add_file(
            zip_file,
            safe_path,
            content,
        )

    @staticmethod
    def _readme_content(
        automation_project: AutomationProject,
    ) -> str:
        return f"""# {automation_project.name}

Automation framework generated by QABook.

## Framework

Python + pytest + Playwright

## Project Structure

    .
    ├── tests/
    │   └── ui/
    ├── pages/
    ├── fixtures/
    ├── utils/
    ├── test_data/
    ├── reports/
    ├── conftest.py
    ├── pytest.ini
    ├── requirements.txt
    ├── .env.example
    ├── .gitignore
    └── README.md

## Setup

Create and activate a virtual environment:

    python -m venv .venv

### Windows

    .venv\\Scripts\\activate

### Linux/macOS

    source .venv/bin/activate

Install dependencies:

    pip install -r requirements.txt

Install Playwright browsers:

    playwright install

## Environment

Copy `.env.example` to `.env` and configure the test environment.

Example:

    BASE_URL=https://example.com
    QABOOK_API_URL=http://127.0.0.1:8000

## Run Tests

Run all automation tests:

    pytest

Run only automation tests:

    pytest -m automation

To connect the test execution to a QABook
Test Run, provide the run ID at runtime:

    pytest --qabook-run-id <TEST_RUN_ID>

Example:

    pytest --qabook-run-id 7

The Test Run ID is runtime execution context
and should not be stored in `.env`.

## QABook Integration

This framework uses QABook Test Cases as the business reference.

Automation mappings are generated from the QABook Automation Project.

Each mapped QABook Test Case generates an automation test
under the configured test file path inside:

    tests/

Each generated test contains the QABook Test Case ID
using the `qabook_test_case` pytest marker.

When pytest is executed with:

    --qabook-run-id <TEST_RUN_ID>

the framework automatically finds the corresponding
QABook Test Execution for each mapped Test Case and
updates its status after the test finishes.

## Page Objects

Reusable UI page behavior should be implemented inside:

    pages/

The `BasePage` class provides common Playwright page
operations that can be shared by page objects.

## Test Data

Test data can be stored inside:

    test_data/

## Reports

Generated reports and execution artifacts can be stored inside:

    reports/
"""

    @staticmethod
    def _requirements_content() -> str:
        return """pytest
playwright
pytest-playwright
python-dotenv
requests
"""

    @staticmethod
    def _pytest_ini_content() -> str:
        return """[pytest]
testpaths = tests

python_files =
    test_*.py
    *_test.py
    tc*.py

markers =
    automation: QABook automation tests
    qabook_test_case(test_case_id): QABook Test Case mapping
"""

    @staticmethod
    def _conftest_content() -> str:
        return """import os

import pytest
from dotenv import load_dotenv

from utils.qabook_client import QABookClient


load_dotenv()


@pytest.fixture(scope="session")
def base_url():
    return os.getenv(
        "BASE_URL",
        "https://example.com",
    )


def pytest_addoption(parser):
    parser.addoption(
        "--qabook-run-id",
        action="store",
        default=None,
        help="QABook Test Run ID for this execution.",
    )


@pytest.fixture(scope="session")
def qabook_run_id(pytestconfig):
    run_id = pytestconfig.getoption(
        "--qabook-run-id"
    )

    if not run_id:
        return None

    return int(run_id)


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()

    if report.when != "call":
        return

    marker = item.get_closest_marker(
        "qabook_test_case"
    )

    if marker is None:
        return

    run_id = item.config.getoption(
        "--qabook-run-id"
    )

    if not run_id:
        return

    test_case_id = marker.args[0]

    try:
        client = QABookClient()

        execution = client.get_execution_by_run_and_test_case(
            int(run_id),
            test_case_id,
        )

        if report.passed:
            execution_status = "Passed"
        elif report.failed:
            execution_status = "Failed"
        else:
            return

        client.update_test_execution(
            execution["id"],
            execution_status,
        )

    except Exception as exc:
        print(
            f"Warning: Failed to update QABook execution: {exc}"
        )
"""

    @staticmethod
    def _base_page_content() -> str:
        return """from playwright.sync_api import Page


class BasePage:
    def __init__(self, page: Page):
        self.page = page

    def navigate(self, url: str) -> None:
        self.page.goto(url)

    def get_title(self) -> str:
        return self.page.title()
"""

    @staticmethod
    def _config_content() -> str:
        return """import os


BASE_URL = os.getenv(
    "BASE_URL",
    "https://example.com",
)

QABOOK_API_URL = os.getenv(
    "QABOOK_API_URL",
    "http://127.0.0.1:8000",
)
"""

    @staticmethod
    def _qabook_client_content() -> str:
        return """import requests

from utils.config import QABOOK_API_URL


class QABookClient:
    def __init__(self):
        self.base_url = QABOOK_API_URL.rstrip("/")

    def get_execution_by_run_and_test_case(
        self,
        run_id: int,
        test_case_id: int,
    ):
        response = requests.get(
            f"{self.base_url}/test-executions/run/"
            f"{run_id}/test-case/{test_case_id}",
            timeout=30,
        )

        response.raise_for_status()

        return response.json()

    def update_test_execution(
        self,
        execution_id: int,
        status: str,
    ):
        response = requests.put(
            f"{self.base_url}/test-executions/{execution_id}",
            json={
                "status": status,
            },
            timeout=30,
        )

        response.raise_for_status()

        return response.json()
"""

    @staticmethod
    def _env_example_content() -> str:
        return """BASE_URL=https://example.com
QABOOK_API_URL=http://127.0.0.1:8000
"""

    @staticmethod
    def _gitignore_content() -> str:
        return """# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd

# Virtual environment
.venv/
venv/
env/

# Environment files
.env

# Playwright
test-results/
playwright-report/
blob-report/

# Reports and artifacts
reports/*
!reports/.gitkeep

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"""