"""add code sequences

Revision ID: 20ea3ccda838
Revises: 7992a9535edc
Create Date: 2026-09-03 16:10:28.811822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ea3ccda838'
down_revision: Union[str, Sequence[str], None] = '7992a9535edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "code_sequences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("next_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type",
            name="uq_code_sequence_entity_type",
        ),
    )

    op.create_index(
        op.f("ix_code_sequences_entity_type"),
        "code_sequences",
        ["entity_type"],
        unique=False,
    )

    op.create_index(
        op.f("ix_code_sequences_id"),
        "code_sequences",
        ["id"],
        unique=False,
    )

    code_sequences = sa.table(
        "code_sequences",
        sa.column("entity_type", sa.String(length=50)),
        sa.column("next_number", sa.Integer()),
    )

    op.bulk_insert(
        code_sequences,
        [
            {"entity_type": "project", "next_number": 1},
            {"entity_type": "requirement", "next_number": 1},
            {"entity_type": "scenario", "next_number": 1},
            {"entity_type": "test_case", "next_number": 1},
            {"entity_type": "test_suite", "next_number": 1},
            {"entity_type": "test_run", "next_number": 1},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_sequences_id'), table_name='code_sequences')
    op.drop_index(op.f('ix_code_sequences_entity_type'), table_name='code_sequences')
    op.drop_table('code_sequences')
    # ### end Alembic commands ###
