"""add execution type to test runs

Revision ID: 2727f3162895
Revises: 764c73ad5c8e
Create Date: 2026-09-02 03:14:02.103881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2727f3162895'
down_revision: Union[str, Sequence[str], None] = '764c73ad5c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('execution_type', sa.String(length=20), server_default='Manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'execution_type')
    # ### end Alembic commands ###
