"""add github connection

Revision ID: 38015078632f
Revises: 28c5333dcbdc
Create Date: 2026-09-04 17:45:14.009294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38015078632f'
down_revision: Union[str, Sequence[str], None] = '28c5333dcbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_project_id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.String(length=100), nullable=False),
    sa.Column('repository_owner', sa.String(length=100), nullable=False),
    sa.Column('repository_name', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_project_id'], ['automation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_project_id')
    )
    op.create_index(op.f('ix_github_connections_id'), 'github_connections', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_github_connections_id'), table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
