"""scenario_code_per_requirement

Revision ID: 66e7dba0c5b2
Revises: 875f6d01d976
Create Date: 2026-07-18 16:21:13.178766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e7dba0c5b2'
down_revision: Union[str, Sequence[str], None] = '875f6d01d976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_scenarios_scenario_code'), table_name='test_scenarios')
    op.create_index(op.f('ix_test_scenarios_scenario_code'), 'test_scenarios', ['scenario_code'], unique=False)
    op.create_unique_constraint('uq_scenario_requirement_code', 'test_scenarios', ['requirement_id', 'scenario_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scenario_requirement_code', 'test_scenarios', type_='unique')
    op.drop_index(op.f('ix_test_scenarios_scenario_code'), table_name='test_scenarios')
    op.create_index(op.f('ix_test_scenarios_scenario_code'), 'test_scenarios', ['scenario_code'], unique=True)
    # ### end Alembic commands ###
