"""Add automation token to test runs

Revision ID: 7992a9535edc
Revises: 90cca210607d
Create Date: 2026-09-03 00:17:11.007325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7992a9535edc'
down_revision: Union[str, Sequence[str], None] = '90cca210607d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('automation_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_test_runs_automation_token'), 'test_runs', ['automation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_automation_token'), table_name='test_runs')
    op.drop_column('test_runs', 'automation_token')
    # ### end Alembic commands ###
