"""requirement_code_per_project

Revision ID: 875f6d01d976
Revises: 27953725f62c
Create Date: 2026-07-17 21:46:15.006636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875f6d01d976'
down_revision: Union[str, Sequence[str], None] = '27953725f62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_requirement_code'), table_name='requirements')
    op.create_index(op.f('ix_requirements_requirement_code'), 'requirements', ['requirement_code'], unique=False)
    op.create_unique_constraint('uq_requirement_project_code', 'requirements', ['project_id', 'requirement_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_requirement_project_code', 'requirements', type_='unique')
    op.drop_index(op.f('ix_requirements_requirement_code'), table_name='requirements')
    op.create_index(op.f('ix_requirements_requirement_code'), 'requirements', ['requirement_code'], unique=True)
    # ### end Alembic commands ###
