"""add automation project and test mapping

Revision ID: 90cca210607d
Revises: 2727f3162895
Create Date: 2026-09-02 16:21:23.773633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cca210607d'
down_revision: Union[str, Sequence[str], None] = '2727f3162895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_automation_projects_id'), 'automation_projects', ['id'], unique=False)
    op.create_table('automation_test_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_project_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_project_id'], ['automation_projects.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_project_id', 'test_case_id', name='uq_automation_project_test_case')
    )
    op.create_index(op.f('ix_automation_test_mappings_id'), 'automation_test_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_test_mappings_id'), table_name='automation_test_mappings')
    op.drop_table('automation_test_mappings')
    op.drop_index(op.f('ix_automation_projects_id'), table_name='automation_projects')
    op.drop_table('automation_projects')
    # ### end Alembic commands ###
