"""add github oauth token fields

Revision ID: 93f91dd6c34c
Revises: 4fb29f0d2792
Create Date: 2026-09-06 16:37:54.317518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f91dd6c34c'
down_revision: Union[str, Sequence[str], None] = '4fb29f0d2792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_connections', sa.Column('github_username', sa.String(length=100), nullable=True))
    op.add_column('github_connections', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('github_connections', sa.Column('github_refresh_token', sa.Text(), nullable=True))
    op.add_column('github_connections', sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('github_connections', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_connections', 'refresh_token_expires_at')
    op.drop_column('github_connections', 'access_token_expires_at')
    op.drop_column('github_connections', 'github_refresh_token')
    op.drop_column('github_connections', 'github_access_token')
    op.drop_column('github_connections', 'github_username')
    # ### end Alembic commands ###
