"""add module priority status to test scenarios

Revision ID: 9ac30150b83c
Revises: 854b421f18e4
Create Date: 2026-07-16 23:47:52.817586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac30150b83c'
down_revision: Union[str, Sequence[str], None] = '854b421f18e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_scenarios', sa.Column('module', sa.String(length=100), nullable=False,  server_default="General",))
    op.add_column('test_scenarios', sa.Column('priority', sa.String(length=20), nullable=False, server_default="Medium",))
    op.add_column('test_scenarios', sa.Column('status', sa.String(length=20), nullable=False,  server_default="Draft",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_scenarios', 'status')
    op.drop_column('test_scenarios', 'priority')
    op.drop_column('test_scenarios', 'module')
    # ### end Alembic commands ###
