"""make qa codes globally unique

Revision ID: b8ee7c8aa441
Revises: 20ea3ccda838
Create Date: 2026-09-03 16:43:12.259401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ee7c8aa441'
down_revision: Union[str, Sequence[str], None] = '20ea3ccda838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_requirement_project_code'), 'requirements', type_='unique')
    op.create_unique_constraint('uq_requirement_code', 'requirements', ['requirement_code'])
    op.drop_constraint(op.f('uq_test_case_scenario_code'), 'test_cases', type_='unique')
    op.create_unique_constraint('uq_test_case_code', 'test_cases', ['test_case_code'])
    op.drop_constraint(op.f('uq_scenario_requirement_code'), 'test_scenarios', type_='unique')
    op.create_unique_constraint('uq_scenario_code', 'test_scenarios', ['scenario_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scenario_code', 'test_scenarios', type_='unique')
    op.create_unique_constraint(op.f('uq_scenario_requirement_code'), 'test_scenarios', ['requirement_id', 'scenario_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_test_case_code', 'test_cases', type_='unique')
    op.create_unique_constraint(op.f('uq_test_case_scenario_code'), 'test_cases', ['scenario_id', 'test_case_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_requirement_code', 'requirements', type_='unique')
    op.create_unique_constraint(op.f('uq_requirement_project_code'), 'requirements', ['project_id', 'requirement_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
